### ISSUE TITLE
请问前端如何进行编译

### ISSUE THREAD

**Issue by limeng32** [loveher147/iotdb-admin#5]
请问前端如何进行编译。我直接使用 npm run build 虽然能编译出页面，但api的调用都显示“网络错误”，请问在本地部署的话编译时是不是要加上什么参数？

**Comment by limeng32** [comment]
发现原因了，需要用nginx来转发api路径。现在又出现一个新问题，就是deploy.md文件上面的图片都是本地的，能不能修改一下呢？

**Comment by limeng32** [comment]
嗯嗯，现在deploy.md文件也能看到了。然后又发现一个问题，backend/src/main/resources/sqlite/iotdb.db 这个文件的编码有点异常，我在windows上无论用哪种编辑器打开都有乱码，麻烦请看一下。

**Comment by benqhy** [comment]
需要使用sqlite3打开。
